strategies:
  - name: ema_cross
    symbol: BTCUSDT
    interval: 1m
    parameters:
      short_window: 9
      long_window: 21
      quantity: 0.001

  - name: macd
    symbol: ETHUSDT
    interval: 1m
    parameters:
      fast_period: 12
      slow_period: 26
      signal_period: 9
      quantity: 0.01

  - name: rsi
    symbol: SOLUSDT
    interval: 1m
    parameters:
      rsi_period: 14
      overbought: 70
      oversold: 30
      quantity: 0.05

  - name: momentum
    symbol: BNBUSDT
    interval: 1m
    parameters:
      lookback: 10
      threshold: 0.02
      quantity: 0.01
