services:
  - type: web
    name: binance-trading-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: binance-db
          property: connectionString

databases:
  - name: binance-db
    region: oregon
